stops = [
    "Zajezdnia NOWY PORT",
    "Władysława IV",
    "Nowy Port Oliwska",
    "Przychodnia",
    "Rybołowców",
    "Kasztanowa",
    "Latarnia Morska",
    "Krasickiego",
    "Brzeźno Dom Zdrojowy",
    "Mazurska",
    "Wczasy",
    "Dworska",
    "al. Płażyńskiego",
    "Grudziądzka",
    "Kolonia Uroda",
    "Kościuszki",
    "Mickiewicza",
    "Reja",
    "Wyspiańskiego",
    "Politechnika",
    "Miszewskiego",
    "Jaśkowa Dolina",
    "Klonowa",
    "Galeria Bałtycka",
    "Wojska Polskiego",
    "Zamenhofa",
    "Zajezdnia",
    "Strzyża PKM",
    "Uniwersytet Gdański",
    "Bażyńskiego",
    "Tetmajera",
    "Derdowskiego",
    "Obrońców Westerplatte",
    "Oliwa",
    "Uczniowska",
    "Gdańska",
    "Sternicza",
    "Na Zaspę",
    "Plac Wolności",
    "Nowy Port Zajezdnia",
    "Zajezdnia WRZESZCZ",
    "Głęboka",
    "Brama Żuławska",
    "Akademia Muzyczna",
    "Chmielna",
    "Żabi Kruk",
    "Okopowa",
    "Brama Wyżynna",
    "Dworzec Główny",
    "Brama Oliwska",
    "Chodowieckiego",
    "Uniwersytet Medyczny",
    "Traugutta",
    "Opera Bałtycka",
    "Lawendowe Wzgórze",
    "Ujeścisko",
    "Częstochowska",
    "Piotrkowska",
    "Łódzka",
    "Przemyska",
    "Wilanowska",
    "Cebertowicza",
    "Cieszyńskiego",
    "Sikorskiego",
    "Chałubińskiego",
    "Odrzańska",
    "Pohulanka",
    "Śródmieście SKM",
    "Plac Komorowskiego",
    "Legionów",
    "Bajana",
    "Żwirki i Wigury",
    "Jana Pawła II",
    "Startowa",
    "Zaspa",
    "Kołobrzeska",
    "Bora-Komorowskiego",
    "Czerwony Dwór",
    "Piastowska",
    "Pomorska",
    "Osiedle Wejhera",
    "Helska",
    "Jelitkowo",
    "Gospody",
    "Pomorska - Osiedle",
    "Subisława",
    "Opacka",
    "Plac Solidarności",
    "Stocznia SKM",
    "Stocznia Północna",
    "Twarda",
    "Węzeł Kliniczna",
    "Swojska",
    "Żaglowa - AmberExpo",
    "Mostostal",
    "Polsat Plus Arena Gdańsk",
    "Śnieżna",
    "Marynarki Polskiej",
    "Politechnika SKM",
    "Nowy Port Góreckiego",
    "Hucisko",
    "Powstańców Warszawskich",
    "Paska",
    "Ciasna",
    "Zakopiańska",
    "Skrajna",
    "Siedlce",
    "Piekarnicza",
    "Belgradzka",
    "Warneńska",
    "Kolumba",
    "Brętowo PKM",
    "Płocka",
    "Łostowice Świętokrzyska",
    "Budapesztańska",
    "Migowo",
    "Królewskie Wzgórze",
    "Łabędzia",
    "Stolema",
    "Zabornia",
    "Chełm Witosa"
]