stops = [
    "zajezdnia nowy port",
    "władysława iv",
    "nowy port góreckiego",
    "marynarki polskiej",
    "śnieżna",
    "polsat plus arena gdańsk",
    "mostostal",
    "żaglowa - amberexpo",
    "swojska",
    "węzeł kliniczna",
    "twarda",
    "stocznia północna",
    "stocznia skm",
    "plac solidarności",
    "dworzec główny",
    "brama wyżynna",
    "śródmieście skm",
    "pohulanka",
    "odrzańska",
    "chałubińskiego",
    "sikorskiego",
    "cieszyńskiego",
    "cebertowicza",
    "wilanowska",
    "przemyska",
    "płocka",
    "łostowice świętokrzyska",
    "brama oliwska",
    "chodowieckiego",
    "uniwersytet medyczny",
    "traugutta",
    "opera bałtycka",
    "wyspiańskiego",
    "reja",
    "mickiewicza",
    "kościuszki",
    "kolonia uroda",
    "grudziądzka",
    "al. płażyńskiego",
    "uczniowska",
    "gdańska",
    "sternicza",
    "brzeźno dom zdrojowy",
    "mazurska",
    "wczasy",
    "dworska",
    "krasickiego",
    "latarnia morska",
    "kasztanowa",
    "na zaspę",
    "plac wolności",
    "nowy port zajezdnia",
    "zajezdnia wrzeszcz",
    "zajezdnia",
    "zamenhofa",
    "wojska polskiego",
    "galeria bałtycka",
    "klonowa",
    "jaśkowa dolina",
    "miszewskiego",
    "politechnika",
    "politechnika skm",
    "nowy port oliwska",
    "przychodnia",
    "rybołowców",
    "strzyża pkm",
    "uniwersytet gdański",
    "bażyńskiego",
    "tetmajera",
    "derdowskiego",
    "obrońców westerplatte",
    "oliwa",
    "opacka",
    "subisława",
    "pomorska - osiedle",
    "osiedle wejhera",
    "helska",
    "jelitkowo",
    "gospody",
    "okopowa",
    "żabi kruk",
    "chmielna",
    "akademia muzyczna",
    "brama żuławska",
    "głęboka",
    "lawendowe wzgórze",
    "ujeścisko",
    "częstochowska",
    "piotrkowska",
    "łódzka",
    "hucisko",
    "powstańców warszawskich",
    "paska",
    "ciasna",
    "zakopiańska",
    "skrajna",
    "siedlce",
    "piekarnicza",
    "belgradzka",
    "warneńska",
    "kolumba",
    "brętowo pkm",
    "plac komorowskiego",
    "legionów",
    "bajana",
    "żwirki i wigury",
    "jana pawła ii",
    "startowa",
    "zaspa",
    "kołobrzeska",
    "bora-komorowskiego",
    "czerwony dwór",
    "piastowska",
    "pomorska",
    "budapesztańska",
    "migowo",
    "królewskie wzgórze",
    "łabędzia",
    "stolema",
    "zabornia",
    "brzeźno plaża"
]